// Generated by CoffeeScript 2.7.0
(function() {
  // This single function handles the socket communication between this 
  // client and the socket server. Few subfunctions let the client (browser):

  // - send a system command to be executed at server side
  // - send a script code to be executed at server side
  // - assign a server variable to be used by the script code (if needed)
  // - read the return data of a system command or a script code execution
  // - return the platform detected at server side, more reliable than client side
  var indexOf = [].indexOf;

  window.socketClient = function() {
    var exec, os, platform, port, read, ref, script, send, serverReply, socket;
    switch (location.hash) {
      case '#BUSY':
        document.body.innerHTML = 'The application is already in use';
        throw new Error('WebScoket already in use');
      case '#ERROR':
        document.body.innerHTML = 'WebSocket connection error';
        throw new Error('WebSocket connection error');
    }
    serverReply = '';
    os = location.hash.split(',')[1];
    port = location.hash.split(',')[2];
    if ((ref = parseInt('0' + port), indexOf.call((function() {
      var results = [];
      for (var i = 1024; i <= 49151; i++){ results.push(i); }
      return results;
    }).apply(this), ref) < 0) || (os !== 'win32' && os !== 'linux' && os !== 'darwin')) {
      document.body.innerHTML = 'This application must be started by the WebSocket server.';
      console.log("Incorrect parameters", os, port);
      throw new Error(document.body.innerHTML);
    }
    socket = new WebSocket(`ws://localhost:${port}/ws`);
    socket.onopen = function(event) {
      return console.log('WebSocket connection established');
    };
    socket.onclose = function(event) {
      console.log('WebSocket connection closed');
      return document.body.innerHTML = 'WebsScoket connection closed';
    };
    // ----------------------------------

    // Return the operating system detected at the server side
    platform = function() {
      return os;
    };
    // Excecute a system command at the server side
    exec = function(command, timeout = 5000) {
      var cmd;
      serverReply = '';
      cmd = JSON.stringify({
        action: 'exec',
        cmd: command,
        timeout: timeout
      });
      return socket.send(cmd);
    };
    // Send a CoffeeScript code (translated to JavaScript) to be executed
    // at the server side with access to Node.js capabilities
    script = function(func, timeout = 5000) {
      var cmd, code;
      code = func.toString();
      serverReply = '';
      cmd = JSON.stringify({
        action: 'script',
        cmd: `(${code})();`,
        timeout: timeout
      });
      return socket.send(cmd);
    };
    // Send data (primitive or object) to server to be saved in the
    // 'data' server variable, usefull before calling script command
    send = function(data) {
      var cmd;
      cmd = JSON.stringify({
        action: 'send',
        cmd: data
      });
      return socket.send(cmd);
    };
    // Wait for server to finish with a system command or script execution
    // and return its result data
    read = function(timeout = 5000) {
      return new Promise(function(resolve) {
        socket.onmessage = function(event) {
          return resolve(event.data.trim());
        };
        // Timeout in milliseconds
        return setTimeout(function() {
          return resolve('#TIMEOUT');
        }, timeout);
      });
    };
    return {platform, exec, script, send, read};
  };

}).call(this);
