// Generated by CoffeeScript 2.7.0
(function() {
  var askConfirm, getVideoFolder, languages, resolutions, server, showAlert;

  server = serverHandler(); // start socket communication with server

  window.onload = function() {
    // Focus on video URL field when page is loaded
    return document.getElementById('videoUrl').focus();
  };

  resolutions = ['360p (LD)', '480p (SD)', '720p (HD)', '1080p (full HD)', '1440p (2K)', '2160p (4K)', 'No cap', 'Audio only'];

  languages = {
    'Afrikaans': 'af',
    'Amharic': 'am',
    'Arabic': 'ar',
    'Basque': 'eu',
    'Bengali': 'bn',
    'Bulgarian': 'bg',
    'Catalan': 'ca',
    'Chinese': 'zh',
    'Croatian': 'hr',
    'Czech': 'cs',
    'Danish': 'da',
    'Dutch': 'nl',
    'English': 'en',
    'Esperanto': 'eo',
    'Estonian': 'et',
    'Filipino': 'fil',
    'Finnish': 'fi',
    'French': 'fr',
    'Galician': 'gl',
    'German': 'de',
    'Greek': 'el',
    'Hebrew': 'he',
    'Hindi': 'hi',
    'Hungarian': 'hu',
    'Icelandic': 'is',
    'Indonesian': 'id',
    'Irish': 'ga',
    'Italian': 'it',
    'Japanese': 'ja',
    'Korean': 'ko',
    'Latvian': 'lv',
    'Lithuanian': 'lt',
    'Malay': 'ms',
    'Norwegian': 'no',
    'Romanian': 'ro',
    'Russian': 'ru',
    'Serbian': 'sr',
    'Slovak': 'sk',
    'Slovenian': 'sl',
    'Spanish': 'es',
    'Swahili': 'sw',
    'Swedish': 'sv',
    'Tamil': 'ta',
    'Telugu': 'te',
    'Thai': 'th',
    'Turkish': 'tr',
    'Ukrainian': 'uk',
    'Vietnamese': 'vi',
    'Welsh': 'cy',
    'Xhosa': 'xh',
    'Zulu': 'zu'
  };

  // *********************************************************************
  showAlert = function(title, icon, msg, textalign = 'center') {
    return Swal.fire({
      title: title,
      html: `<div style='text-align: ${textalign}; font-size: 16px;'>${msg}</div>`,
      icon: icon,
      confirmButtonText: 'OK',
      allowOutsideClick: false
    });
  };

  // --------------------------------------
  askConfirm = function(title, icon, msg, textalign = 'center') {
    return Swal.fire({
      title: title,
      html: `<div style='text-align: ${textalign}; font-size: 16px;'>${msg}</div>`,
      icon: icon,
      showCancelButton: true,
      confirmButtonText: 'Yes',
      cancelButtonText: 'No',
      focusCancel: true,
      allowOutsideClick: false
    });
  };

  (function() {    // --------------------------------------
    var brTag, container, i, index, label, len, radio, resolution, results1;
// Create radio button panel with all supported video resolutions
    results1 = [];
    for (index = i = 0, len = resolutions.length; i < len; index = ++i) {
      resolution = resolutions[index];
      // Select the fieldset container where radio buttons are grouped
      container = document.querySelector('.radio-section');
      // Create a radio button
      radio = document.createElement('input');
      radio.type = 'radio';
      radio.id = index; // unique id
      radio.name = 'resolutions'; // group name
      radio.value = resolution;
      if (resolution === '720p (HD)') {
        radio.checked = true;
      }
      // Create label element for the radio button
      label = document.createElement('label');
      label.setAttribute('for', resolution);
      label.textContent = resolution;
      // Append radio button and label to the container
      container.appendChild(radio);
      container.appendChild(label);
      // Add line break for layout
      brTag = document.createElement('br');
      results1.push(container.appendChild(brTag));
    }
    return results1;
  })();

  (function() {    // --------------------------------------
    var checkbox, container, label, language, results1;
    // Create checkbox panel with all supported languages
    container = document.querySelector('.checkbox-grid');
    results1 = [];
    for (language in languages) {
      // Create a label element
      label = document.createElement('label');
      // Create the checkbox input element
      checkbox = document.createElement('input');
      checkbox.type = 'checkbox';
      checkbox.name = 'language';
      checkbox.value = language;
      if (language === 'English') {
        checkbox.checked = true;
      }
      // Append the checkbox into the label
      label.appendChild(checkbox);
      // Add the label text node (for example "English")
      label.appendChild(document.createTextNode(language));
      // Append the label to the container
      results1.push(container.appendChild(label));
    }
    return results1;
  })();

  (async function() {    // --------------------------------------
    var match, msg, reply, result;
    // Check if new server version is available in 'latestServerCode' variable
    match = window.latestServerCode.match(/#\d+(\.\d+)?/);
    if (match == null) {
      return;
    }
    if (match[0] > server.version()) {
      msg = `The WebSocket server has an update available.<br>
<br>
Do you want to update now?<br><br>`;
      reply = (await askConfirm('', 'warning', msg));
      if (reply.isConfirmed) {
        server.update(window.latestServerCode);
        result = (await server.read());
        if (result === 'Success') {
          msg = `The update was successfull!<br>
<br>
The application must be restarted for the update to take effect.`;
        } else {
          msg = `The update has failed.<br>
<br>
This is problably due to unexpected file/folder permissions.`;
        }
        return showAlert('Update status', '', msg);
      }
    }
  })();

  // --------------------------------------
  // 'Help' button
  document.getElementById('help').onclick = function() {
    var msg;
    msg = window.help;
    if (server.platform() === 'linux') {
      // Add Linux 'xterm' to the list of dependencies
      msg = msg.replace('</pre>', '- <b>xterm</b>  terminal utility</pre>');
    }
    return showAlert('Help', '', msg, 'left');
  };

  // --------------------------------------
  // 'About' button
  document.getElementById('about').onclick = function() {
    var msg;
    msg = `A web interface for <i>yt-dlp</i> video download utility<br>
<br>
\u00A9 2025 - RonLinu`;
    return showAlert('YDownloader 1.1', '', msg);
  };

  // --------------------------------------
  // 'Check dependencies' button
  document.getElementById('dependencies').onclick = async function() {
    var failCross, gatherResults, goodCheck, missingCount, plural, result, results;
    results = '';
    missingCount = 0;
    failCross = '&#x2718;';
    goodCheck = '&#x2714;';
    gatherResults = function(name, result) {
      var regex;
      results += `<b>${name}&nbsp;</b><span style='color: `;
      regex = /is not|not found|#TIMEOUT/i;
      if (regex.test(result)) {
        results += `red;'>${failCross}</span><br>`;
        return missingCount++;
      } else {
        return results += `green;'>${goodCheck}</span><br>`;
      }
    };
    // Show a wait dialog with a progress animation
    Swal.fire({
      title: 'Please wait',
      text: 'Checking is in progress...',
      showConfirmButton: false,
      allowOutsideClick: false,
      didOpen: function() {
        return Swal.showLoading();
      }
    });
    // Start sequence of tests, one dependency at a time
    server.exec('yt-dlp --version');
    result = (await server.read());
    gatherResults('yt-dlp', result);
    server.exec('ffmpeg -version');
    result = (await server.read());
    gatherResults('ffmpeg', result);
    if (server.platform() === 'linux') {
      server.exec('xterm -version');
      result = (await server.read());
      gatherResults('xterm ', result);
    }
    if (missingCount) {
      plural = missingCount > 1 ? 'cies are' : 'cy is';
      results += `\n ${missingCount} dependen${plural} missing!`;
    } else {
      results += '\nAll good!';
    }
    Swal.close();
    return showAlert('Status of dependencies', '', `<pre>${results}</pre>`);
  };

  // --------------------------------------
  getVideoFolder = function() {
    switch (server.platform()) {
      case 'win32':
        return '%USERPROFILE%\\Videos';
      case 'linux':
        return '$HOME/Videos';
      case 'darwin':
        return '$HOME/Movies';
    }
  };

  // --------------------------------------
  // 'Open video folder' button
  document.getElementById('openfolder').onclick = async function() {
    var answer, cmd, msg, videoFolder;
    videoFolder = getVideoFolder();
    cmd = (function() {
      switch (server.platform()) {
        case 'win32':
          return `explorer "${videoFolder}" `;
        case 'linux':
          return `xdg-open "${videoFolder}" `;
        case 'darwin':
          return `open "${videoFolder}" `;
      }
    })();
    msg = `If the video folder does not appear,<br>
look behind the browser window or in the task bar.<br>
<br>
<i>click Ok to open the folder</i>`;
    answer = (await showAlert('Notice', '', msg));
    if (answer.isConfirmed) {
      return server.exec(cmd);
    }
  };

  // --------------------------------------------------------------------
  // 'Download' button click
  document.getElementById('download').onclick = function() {
    var abbreviations, checked, checkedLanguages, final_cmd, i, index, isValidUrl, len, option_merging, option_playlist, option_resolution, option_subtitles, resolution, selectedResolution, subtitles, url, ytdlp_cmd;
    // Local function to check URL validity
    isValidUrl = function(url) {
      var urlObj;
      try {
        urlObj = new URL(url);
        return urlObj.protocol === 'http:' || urlObj.protocol === 'https:';
      } catch (error) {
        return false;
      }
    };
    url = document.getElementById('videoUrl').value.trim();
    if (!url) {
      showAlert('', 'error', 'The Video URL field is empty.');
      return;
    } else if (!isValidUrl(url)) {
      showAlert('', 'error', 'The Video URL is not valid.');
      return;
    }
    option_resolution = '';
    option_subtitles = '';
    option_merging = '';
    option_playlist = '';
    
    // Ignore playlist, just download the main video (not reliable)
    index = url.indexOf("&list");
    if (index !== -1) {
      option_playlist = '--no-playlist ';
    }
    selectedResolution = document.querySelector('input[name="resolutions"]:checked').value;
    option_resolution = (function() {
      switch (selectedResolution) {
        case 'No cap':
          return '-f bestvideo+bestaudio/best '; // '-f best '
        case 'Audio only':
          return '-x --audio-format mp3 ';
        default:
          resolution = parseInt(selectedResolution);
          return '-f "bv[height<=' + resolution + ']+ba/b[height<=' + resolution + ']" ';
      }
    })();
    if (selectedResolution !== 'Audio only') {
      option_merging = '--merge-output-format mkv --remux-video mkv ';
      // Extract abbreviations of selected subtitle languages into an array
      checkedLanguages = document.querySelectorAll('input[name="language"]:checked');
      abbreviations = [];
      for (i = 0, len = checkedLanguages.length; i < len; i++) {
        checked = checkedLanguages[i];
        abbreviations.push(languages[checked.value]);
      }
      if (abbreviations.length) {
        subtitles = abbreviations.join(",");
        option_subtitles = '--write-sub --ignore-errors --write-auto-subs --sub-langs ' + subtitles + ' --embed-subs ';
      }
    }
    ytdlp_cmd = 'yt-dlp ' + '--concurrent-fragments 2 ' + '--no-warnings ' + '-P "' + getVideoFolder() + '" ' + option_resolution + option_playlist + option_subtitles + option_merging + '--embed-metadata ' + '--buffer-size 16M ' + '"' + url + '"';
    console.log(ytdlp_cmd);
    final_cmd = (function() {
      switch (server.platform()) {
        case 'win32':
          return `cmd /c start "" cmd /k ${ytdlp_cmd} `;
        case 'linux':
          return `xterm -geometry 150x24 -e sh -c '${ytdlp_cmd}; echo; bash' `;
        case 'darwin':
          return `osascript -e 'tell application "Terminal" to do script "${ytdlp_cmd}; do shell'" `;
      }
    })();
    return server.exec(final_cmd, 0); // 0 = no timeout to download videos
  };

}).call(this);
