// Generated by CoffeeScript 2.7.0
  // ******************* WEBSOCKET SERVER HANDLER ************************
var askConfirm, getVideoFolder, languages, resolutions, server, serverHandler, showAlert,
  indexOf = [].indexOf;

serverHandler = function() {
  var coffee, exec, js, os, platform, port, ref, reply, serverReply, socket;
  switch (location.hash) {
    case '#BUSY':
      document.body.innerHTML = 'The application is already in use';
      throw new Error('WebScoket already in use');
    case '#ERROR':
      document.body.innerHTML = 'WebSocket connection error';
      throw new Error('WebSocket connection error');
  }
  serverReply = '';
  os = location.hash.split(',')[1];
  port = location.hash.split(',')[2];
  if ((ref = parseInt('0' + port), indexOf.call((function() {
    var results1 = [];
    for (var i = 1024; i <= 49151; i++){ results1.push(i); }
    return results1;
  }).apply(this), ref) < 0) || (os !== 'win32' && os !== 'linux' && os !== 'darwin')) {
    document.body.innerHTML = 'This application must be started by the WebSocket server.';
    console.log("Incorrect parameters", os, port);
    throw new Error(document.body.innerHTML);
  }
  socket = new WebSocket(`ws://localhost:${port}/ws`);
  socket.onopen = function(event) {
    return console.log('WebSocket connection established');
  };
  socket.onclose = function(event) {
    console.log('WebSocket connection closed');
    return document.body.innerHTML = 'WebsScoket connection closed';
  };
  // ----------------------------------
  platform = function() {
    return os;
  };
  exec = function(command, timeout = 5000) {
    var cmd;
    serverReply = '';
    cmd = JSON.stringify({
      action: 'exec',
      cmd: command,
      timeout: timeout
    });
    return socket.send(cmd);
  };
  js = function(command, timeout = 5000) {
    var cmd;
    serverReply = '';
    cmd = JSON.stringify({
      action: 'js',
      cmd: command,
      timeout: timeout
    });
    return socket.send(cmd);
  };
  coffee = function(func, timeout = 5000) {
    var code, command;
    code = func.toString();
    command = `(${code})();`;
    return js(command, timeout);
  };
  reply = function(timeout = 5000) {
    return new Promise(function(resolve) {
      socket.onmessage = function(event) {
        return resolve(event.data.trim());
      };
      // Timeout in milliseconds
      return setTimeout(function() {
        return resolve('#TIMEOUT');
      }, timeout);
    });
  };
  return {platform, exec, js, coffee, reply};
};

// --- Start handler as a closure ---
server = serverHandler();

// ********************* END OF SERVER HANDLER *************************
window.onload = function() {
  // Focus on video URL field when page is loaded
  return document.getElementById('videoUrl').focus();
};

// --------------------------------------
languages = {
  'Afrikaans': 'af',
  'Amharic': 'am',
  'Arabic': 'ar',
  'Basque': 'eu',
  'Bengali': 'bn',
  'Bulgarian': 'bg',
  'Catalan': 'ca',
  'Chinese': 'zh',
  'Croatian': 'hr',
  'Czech': 'cs',
  'Danish': 'da',
  'Dutch': 'nl',
  'English': 'en',
  'Esperanto': 'eo',
  'Estonian': 'et',
  'Filipino': 'fil',
  'Finnish': 'fi',
  'French': 'fr',
  'Galician': 'gl',
  'German': 'de',
  'Greek': 'el',
  'Hebrew': 'he',
  'Hindi': 'hi',
  'Hungarian': 'hu',
  'Icelandic': 'is',
  'Indonesian': 'id',
  'Irish': 'ga',
  'Italian': 'it',
  'Japanese': 'ja',
  'Korean': 'ko',
  'Latvian': 'lv',
  'Lithuanian': 'lt',
  'Malay': 'ms',
  'Norwegian': 'no',
  'Romanian': 'ro',
  'Russian': 'ru',
  'Serbian': 'sr',
  'Slovak': 'sk',
  'Slovenian': 'sl',
  'Spanish': 'es',
  'Swahili': 'sw',
  'Swedish': 'sv',
  'Tamil': 'ta',
  'Telugu': 'te',
  'Thai': 'th',
  'Turkish': 'tr',
  'Ukrainian': 'uk',
  'Vietnamese': 'vi',
  'Welsh': 'cy',
  'Xhosa': 'xh',
  'Zulu': 'zu'
};

resolutions = ['360p (LD)', '480p (SD)', '720p (HD)', '1080p (full HD)', '1440p (2K)', '2160p (4K)', 'No cap', 'Audio only'];

(function() {  // *********************************************************************
  var checkbox, container, label, language, results1;
  // Create checkbox panel with all supported languages
  container = document.querySelector('.checkbox-grid');
  results1 = [];
  for (language in languages) {
    // Create a label element
    label = document.createElement('label');
    // Create the checkbox input element
    checkbox = document.createElement('input');
    checkbox.type = 'checkbox';
    checkbox.name = 'language';
    checkbox.value = language;
    if (language === 'English') {
      checkbox.checked = true;
    }
    // Append the checkbox into the label
    label.appendChild(checkbox);
    // Add the label text node (for example "English")
    label.appendChild(document.createTextNode(language));
    // Append the label to the container
    results1.push(container.appendChild(label));
  }
  return results1;
})();

(function() {  // --------------------------------------
  var brTag, container, i, index, label, len, radio, resolution, results1;
// Create radio button panel with all supported video resolutions
  results1 = [];
  for (index = i = 0, len = resolutions.length; i < len; index = ++i) {
    resolution = resolutions[index];
    // Select the fieldset container where radio buttons are grouped
    container = document.querySelector('.radio-section');
    // Create a radio button
    radio = document.createElement('input');
    radio.type = 'radio';
    radio.id = index; // unique id
    radio.name = 'resolutions'; // group name
    radio.value = resolution;
    if (resolution === '720p (HD)') {
      radio.checked = true;
    }
    // Create label element for the radio button
    label = document.createElement('label');
    label.setAttribute('for', resolution);
    label.textContent = resolution;
    // Append radio button and label to the container
    container.appendChild(radio);
    container.appendChild(label);
    // Add line break for layout
    brTag = document.createElement('br');
    results1.push(container.appendChild(brTag));
  }
  return results1;
})();

// --------------------------------------
showAlert = function(title, icon, msg, textalign = 'center') {
  return Swal.fire({
    title: title,
    html: `<div style='text-align: ${textalign}; font-size: 16px;'>${msg}</div>`,
    icon: icon,
    confirmButtonText: 'OK',
    allowOutsideClick: false
  });
};

// --------------------------------------
askConfirm = function(title, icon, msg, textalign = 'center') {
  return Swal.fire({
    title: title,
    html: `<div style='text-align: ${textalign}; font-size: 16px;'>${msg}</div>`,
    icon: icon,
    showCancelButton: true,
    confirmButtonText: 'Yes',
    cancelButtonText: 'No',
    focusCancel: true,
    allowOutsideClick: false
  });
};

// --------------------------------------
getVideoFolder = function() {
  switch (server.platform()) {
    case 'win32':
      return '%USERPROFILE%\\Videos';
    case 'linux':
      return '$HOME/Videos';
    case 'darwin':
      return '$HOME/Movies';
  }
};

// --------------------------------------------------------------------
// 'Open video folder' button click
document.getElementById('openfolder').onclick = async function() {
  var cmd, msg, videoFolder;
  videoFolder = getVideoFolder();
  cmd = (function() {
    switch (server.platform()) {
      case 'win32':
        return `explorer "${videoFolder}" `;
      case 'linux':
        return `xdg-open "${videoFolder}" `;
      case 'darwin':
        return `open "${videoFolder}" `;
    }
  })();
  msg = 'If the video folder does not appear,<br>';
  msg += 'look behind the browser window or in the task bar.<br>';
  msg += '<br><i>click Ok to open the folder</i>';
  await showAlert('Notice', '', msg);
  return server.exec(cmd);
};

// --------------------------------------------------------------------
// 'About' button click
document.getElementById('about').onclick = async function() {
  var msg;
  msg = `A web interface for <i>yt-dlp</i> video download utility
<br><br>
\u00A9 2025 - RonLinu`;
  return (await showAlert('YDownloader 0.9', '', msg));
};


// --------------------------------------------------------------------
// 'Check dependencies' button click
document.getElementById('dependencies').onclick = async function() {
  var failCross, gather_results, goodCheck, missing, plural, result, results;
  results = '';
  failCross = '&#x2718;';
  goodCheck = '&#x2714;';
  gather_results = function(name, result) {
    results += `<b>${name}&nbsp;</b><span style='color: `;
    if (/is not|not found|#TIMEOUT/i.test(result)) {
      return results += `red;'>${failCross}</span><br>`;
    } else {
      return results += `green;'>${goodCheck}</span><br>`;
    }
  };
  // Show a wait dialog with a progress animation
  Swal.fire({
    title: 'Please wait',
    text: 'Checking is in progress...',
    showConfirmButton: false,
    allowOutsideClick: false,
    didOpen: function() {
      return Swal.showLoading();
    }
  });
  // Start sequence of tests, one dependency at a time
  server.exec('yt-dlp --version');
  result = (await server.reply());
  gather_results('yt-dlp', result);
  server.exec('ffmpeg -version');
  result = (await server.reply());
  gather_results('ffmpeg', result);
  if (server.platform() === 'linux') {
    server.exec('xterm -version');
    result = (await server.reply());
    gather_results('xterm ', result);
  }
  if (results.indexOf(failCross) === -1) {
    results += '\nAll good!';
  } else {
    missing = results.split(failCross).length - 1;
    plural = missing > 1 ? 'dependencies are' : 'dependency is';
    results += `\n ${missing} ${plural} missing!`;
  }
  Swal.close();
  return showAlert('Status of dependencies', '', `<pre>${results}</pre>`);
};

// --------------------------------------------------------------------
// 'Help' button click
document.getElementById('help').onclick = function() {
  var msg;
  msg = window.HELP;
  if (server.platform() === 'linux') {
    // Add Linux 'xterm' to the list of dependencies
    msg = msg.replace('</pre>', '- <b>xterm</b>  terminal utility</pre>');
  }
  return showAlert('Help', '', msg, 'left');
};

// --------------------------------------
// 'Download' button click
document.getElementById('download').onclick = function() {
  var abbreviations, checked, checkedLanguages, final_cmd, i, index, isValidUrl, len, option_merging, option_resolution, option_subtitles, resolution, selectedResolution, subtitles, url, videoFolder, ytdlp_cmd;
  // Local function to check URL validity
  isValidUrl = function(url) {
    var urlObj;
    try {
      urlObj = new URL(url);
      return urlObj.protocol === 'http:' || urlObj.protocol === 'https:';
    } catch (error) {
      return false;
    }
  };
  // ------------------------------------
  url = document.getElementById('videoUrl').value.trim();
  if (!url) {
    showAlert('', 'error', 'The Video URL field is empty.');
    return;
  } else if (!isValidUrl(url)) {
    showAlert('', 'error', 'The Video URL is not valid.');
    return;
  }
  // Remove any playlist, just download the main video
  index = url.indexOf("?list");
  if (index !== -1) {
    url = url.slice(0, index);
  }
  option_resolution = '';
  option_subtitles = '';
  option_merging = '';
  selectedResolution = document.querySelector('input[name="resolutions"]:checked').value;
  if (selectedResolution === 'No cap') {
    option_resolution = '-f best ';
  } else if (selectedResolution === 'Audio only') {
    option_resolution = '-x --audio-format mp3 ';
  } else {
    // Extract resolution number
    resolution = parseInt(selectedResolution);
    option_resolution = '-f "bv[height<=' + resolution + ']+ba/b[height<=' + resolution + ']" ';
  }
  if (selectedResolution !== 'Audio only') {
    option_merging = '--merge-output-format mkv --remux-video mkv ';
    // Extract abbreviations of selected subtitle languages into an array
    checkedLanguages = document.querySelectorAll('input[name="language"]:checked');
    abbreviations = [];
    for (i = 0, len = checkedLanguages.length; i < len; i++) {
      checked = checkedLanguages[i];
      abbreviations.push(languages[checked.value]);
    }
    if (abbreviations.length) {
      subtitles = abbreviations.join(",");
      option_subtitles = '--write-sub --ignore-errors --write-auto-subs --sub-langs ' + subtitles + ' --embed-subs ';
    }
  }
  videoFolder = getVideoFolder();
  ytdlp_cmd = 'yt-dlp ' + '--concurrent-fragments 2 ' + '--no-warnings ' + '-P "' + videoFolder + '" ' + option_resolution + option_subtitles + option_merging + '--embed-metadata ' + '--buffer-size 16M ' + '"' + url + '"';
  final_cmd = (function() {
    switch (server.platform()) {
      case 'win32':
        return `cmd /c start "" cmd /k ${ytdlp_cmd} `;
      case 'linux':
        return `xterm -geometry 150x24 -e sh -c '${ytdlp_cmd}; echo; bash' `;
      case 'darwin':
        return `osascript -e 'tell application "Terminal" to do script "${ytdlp_cmd}; do shell'" `;
    }
  })();
  return server.exec(final_cmd, 0); // 0 = no timeout to download videos
};
