// Generated by CoffeeScript 2.7.0
  // ********************** WEBSOCKET HANDLING ***************************
var askConfirm, getOS, getVideoFolder, languages, openVideoFolder, resolutions, showAlert, socket, socket_send,
  indexOf = [].indexOf;

socket = null;

(function() {
  var msg, port, ref;
  if (location.hash === '#BUSY') {
    document.body.innerHTML = 'The WebSocket is already in use.';
    throw new Error("Stop execution");
  }
  port = location.hash.substring(1);
  if (ref = parseInt('0' + port), indexOf.call([8080, 8081, 8082, 8083, 8084, 8085, 8086, 8087, 8088, 8089], ref) < 0) {
    msg = 'This web application must be started with the WebSocket server. ';
    document.body.innerHTML = msg;
    throw new Error("Stop execution");
  }
  // This will have the server to close after 5 sec
  socket = new WebSocket(`ws://localhost:${port}/ws`);
  socket.onopen = function(event) {
    return console.log('WebSocket connection established');
  };
  socket.onclose = function(event) {
    console.log('WebSocket closed');
    return document.body.innerHTML = 'The application has been closed.';
  };
  return socket.onmessage = function(event) {
    // Future dispatcher for received messages...
    return console.log(event.data);
  };
})();


// --------------------------------------
socket_send = function(action, command, tag) {
  var cmd;
  cmd = JSON.stringify({
    id: location.hash, // use full fragment as identifier
    action: action,
    cmd: command,
    tag: tag
  });
  return socket.send(cmd);
};

// ******************* END OF WEBSOCKET HANDLING ***********************
window.addEventListener('beforeunload', function(event) {
  // Terminate the external socket server program
  return socket_send('exit', '', 'EXIT');
});

// --------------------------------------
window.onload = function() {
  // Conveniently focus on video URL field
  return document.getElementById('videoUrl').focus();
};

// --------------------------------------
languages = {
  'Afrikaans': 'af',
  'Amharic': 'am',
  'Arabic': 'ar',
  'Basque': 'eu',
  'Bengali': 'bn',
  'Bulgarian': 'bg',
  'Catalan': 'ca',
  'Chinese': 'zh',
  'Croatian': 'hr',
  'Czech': 'cs',
  'Danish': 'da',
  'Dutch': 'nl',
  'English': 'en',
  'Esperanto': 'eo',
  'Estonian': 'et',
  'Filipino': 'fil',
  'Finnish': 'fi',
  'French': 'fr',
  'Galician': 'gl',
  'German': 'de',
  'Greek': 'el',
  'Hebrew': 'he',
  'Hindi': 'hi',
  'Hungarian': 'hu',
  'Icelandic': 'is',
  'Indonesian': 'id',
  'Irish': 'ga',
  'Italian': 'it',
  'Japanese': 'ja',
  'Korean': 'ko',
  'Latvian': 'lv',
  'Lithuanian': 'lt',
  'Malay': 'ms',
  'Norwegian': 'no',
  'Romanian': 'ro',
  'Russian': 'ru',
  'Serbian': 'sr',
  'Slovak': 'sk',
  'Slovenian': 'sl',
  'Spanish': 'es',
  'Swahili': 'sw',
  'Swedish': 'sv',
  'Tamil': 'ta',
  'Telugu': 'te',
  'Thai': 'th',
  'Turkish': 'tr',
  'Ukrainian': 'uk',
  'Vietnamese': 'vi',
  'Welsh': 'cy',
  'Xhosa': 'xh',
  'Zulu': 'zu'
};

resolutions = ['360p (LD)', '480p (SD)', '720p (HD)', '1080p (full HD)', '1440p (2K)', '2160p (4K)', 'No cap', 'Audio only'];

(function() {  // *********************************************************************
  var checkbox, container, label, language, results;
  // Create checkbox panel with all supported languages
  container = document.querySelector('.checkbox-grid');
  results = [];
  for (language in languages) {
    // Create a label element
    label = document.createElement('label');
    // Create the checkbox input element
    checkbox = document.createElement('input');
    checkbox.type = 'checkbox';
    checkbox.name = 'language';
    checkbox.value = language;
    if (language === 'English') {
      checkbox.checked = true;
    }
    // Append the checkbox into the label
    label.appendChild(checkbox);
    // Add the label text node (for example "English")
    label.appendChild(document.createTextNode(language));
    // Append the label to the container
    results.push(container.appendChild(label));
  }
  return results;
})();

(function() {  // --------------------------------------
  var brTag, container, i, index, label, len, radio, resolution, results;
// Create radio button panel with all supported video resolutions
  results = [];
  for (index = i = 0, len = resolutions.length; i < len; index = ++i) {
    resolution = resolutions[index];
    // Select the fieldset container where radio buttons are grouped
    container = document.querySelector('.radio-section');
    // Create a radio button
    radio = document.createElement('input');
    radio.type = 'radio';
    radio.id = index; // unique id
    radio.name = 'resolutions'; // group name
    radio.value = resolution;
    if (resolution === '720p (HD)') {
      radio.checked = true;
    }
    // Create label element for the radio button
    label = document.createElement('label');
    label.setAttribute('for', resolution);
    label.textContent = resolution;
    // Append radio button and label to the container
    container.appendChild(radio);
    container.appendChild(label);
    // Add line break for layout
    brTag = document.createElement('br');
    results.push(container.appendChild(brTag));
  }
  return results;
})();

// --------------------------------------
showAlert = function(title, icon, msg, textalign = 'center') {
  return Swal.fire({
    title: title,
    html: `<div style='text-align: ${textalign}; font-size: 16px;'>${msg}</div>`,
    icon: icon,
    confirmButtonText: 'OK'
  });
};

// --------------------------------------
askConfirm = function(title, icon, msg) {
  return Swal.fire({
    title: title,
    html: msg,
    icon: icon,
    showCancelButton: true,
    confirmButtonText: 'Yes',
    cancelButtonText: 'No',
    focusCancel: true
  });
};

// --------------------------------------
getOS = function() {
  var platform;
  platform = navigator.platform;
  switch (false) {
    case !(platform.indexOf('Win') > -1):
      return 'windows';
    case !(platform.indexOf('Linux') > -1):
      return 'linux';
    case !(platform.indexOf('Mac') > -1):
      return 'macos';
    default:
      return 'unknown';
  }
};

// --------------------------------------
getVideoFolder = function() {
  switch (getOS()) {
    case 'windows':
      return '%USERPROFILE%\\Videos';
    case 'linux':
      return '$HOME/Videos';
    case 'macos':
      return '$HOME/Movies';
  }
};

// --------------------------------------------------------------------
openVideoFolder = function() {
  var once;
  once = true; // closure variable
  return async function() {
    var cmd, msg, videoFolder;
    videoFolder = getVideoFolder();
    cmd = (function() {
      switch (getOS()) {
        case 'windows':
          return `explorer "${videoFolder}" `;
        case 'linux':
          return `xdg-open "${videoFolder}" `;
        case 'macos':
          return `open "${videoFolder}" `;
      }
    })();
    if (once) {
      once = false;
      msg = 'If you don’t see the video folder showing up,<br>';
      msg += 'look in your task bar OR behind the browser window.<br>';
      msg += '<br><i>This note is shown only once per session</i>';
      await showAlert('Quick note', '', msg);
    }
    return socket_send('run', cmd, 'OPEN FOLDER');
  };
};

// 'Open video folder' button click
document.getElementById('openfolder').onclick = openVideoFolder();

// --------------------------------------------------------------------
// 'About' button click
document.getElementById('about').onclick = function() {
  var msg;
  msg = `YDownloader 1.11<br><br>
Using CoffeeScript 2.7<br><br>
\u00A9 2025 - RonLinu`;
  return showAlert('', '', msg);
};

// --------------------------------------------------------------------
// 'Help' button click
document.getElementById('help').onclick = function() {
  return showAlert('Help', '', window.HELP, 'left');
};

// --------------------------------------------------------------------
// 'Exit' button click
document.getElementById('exit').onclick = async function() {
  var result;
  result = (await askConfirm('', 'question', 'This will terminate the application.<br><br>Are you sure?'));
  if (result.isConfirmed) {
    return socket.close();
  }
};

// --------------------------------------
// 'Generate yt-dlp command' button click
document.getElementById('download').onclick = function() {
  var abbreviations, checked, checkedLanguages, final_cmd, i, index, isValidUrl, len, option_merging, option_resolution, option_subtitles, resolution, selectedResolution, subtitles, url, videoFolder, ytdlp_cmd;
  // Local function to check URL validity
  isValidUrl = function(string) {
    var urlObj;
    try {
      urlObj = new URL(string);
      return urlObj.protocol === 'http:' || urlObj.protocol === 'https:';
    } catch (error) {
      return false;
    }
  };
  // ------------------------------------
  url = document.getElementById('videoUrl').value.trim();
  if (!url) {
    showAlert('', 'error', 'The Video URL field is empty.');
    return;
  } else if (!isValidUrl(url)) {
    showAlert('', 'error', 'The Video URL is invalid.');
    return;
  }
  // Remove any playlist, just download the main video
  index = url.indexOf("?list");
  if (index !== -1) {
    url = url.slice(0, index);
  }
  option_resolution = '';
  option_subtitles = '';
  option_merging = '';
  selectedResolution = document.querySelector('input[name="resolutions"]:checked').value;
  if (selectedResolution === 'No cap') {
    option_resolution = '-f best ';
  } else if (selectedResolution === 'Audio only') {
    option_resolution = '-x --audio-format mp3 ';
  } else {
    // Extract resolution number
    resolution = parseInt(selectedResolution);
    option_resolution = '-f "bv[height<=' + resolution + ']+ba/b[height<=' + resolution + ']" ';
  }
  if (selectedResolution !== 'Audio only') {
    option_merging = '--merge-output-format mkv --remux-video mkv ';
    // Extract abbreviations of selected subtitle languages into an array
    checkedLanguages = document.querySelectorAll('input[name="language"]:checked');
    abbreviations = [];
    for (i = 0, len = checkedLanguages.length; i < len; i++) {
      checked = checkedLanguages[i];
      abbreviations.push(languages[checked.value]);
    }
    if (abbreviations.length) {
      subtitles = abbreviations.join(",");
      option_subtitles = '--write-sub --ignore-errors --write-auto-subs --sub-langs ' + subtitles + ' --embed-subs ';
    }
  }
  videoFolder = getVideoFolder();
  ytdlp_cmd = 'yt-dlp ' + '--concurrent-fragments 2 ' + '--no-warnings ' + '-P "' + videoFolder + '" ' + option_resolution + option_subtitles + option_merging + '--embed-metadata ' + '--buffer-size 16M ' + '"' + url + '"';
  final_cmd = (function() {
    switch (getOS()) {
      case 'windows':
        return `cmd /c start "" cmd /k ${ytdlp_cmd} `;
      case 'linux':
        return `xterm -geometry 150x24 -e sh -c '${ytdlp_cmd}; echo; bash' `;
      case 'macos':
        return `osascript -e 'tell application "Terminal" to do script "${ytdlp_cmd}; do shell'" `;
    }
  })();
  return socket_send('run', final_cmd, 'YT-DLP');
};
