// Generated by CoffeeScript 2.7.0
(function() {
  var WebSocket, activeClient, data, exec, launchBrowser, openBrowser, shutdown, socketport, timeout, webpage, wss;

  webpage = process.argv[2];

  socketport = process.argv[3];

  data = null;

  timeout = true; // flag a delay for client to respond

  activeClient = null; // only one client accepted at a time

  if (socketport === '' || webpage === '') {
    console.log('Syntax: node websocket.js <web_app_url> <socket_port>');
    process.exit(0);
  }

  WebSocket = require('ws'); // to install: npm install ws

  ({exec} = require('child_process'));

  wss = new WebSocket.Server({
    port: socketport
  });

  // --------------------------------------
  wss._server.on('listening', function() {
    var fragment;
    // Port opened successfully
    console.log('WebSocket server listening on port', socketport);
    // Client (browser) must respond within 10 sec or server will close
    setTimeout(shutdown, 10000);
    // Launch client (browser)
    fragment = '#,' + process.platform + ',' + socketport;
    return launchBrowser(webpage, fragment);
  });

  // --------------------------------------
  wss.on('error', function(err) {
    var firstline;
    if (err.code === 'EADDRINUSE') {
      console.error('Port', socketport, 'is already in use');
      return launchBrowser(webpage, '#BUSY');
    } else {
      firstline = err.message.split('\n')[0];
      console.error('WebSocket server error:', firstline);
      return launchBrowser(webpage, '#ERROR');
    }
  });

  // --------------------------------------
  // When client connects
  wss.on('connection', function(ws) {
    if (activeClient) {
      ws.close(1000, 'Only one client allowed at a time'); // 1000=nomal close
      return;
    }
    activeClient = ws;
    console.log('Client connected');
    timeout = false; // cancel automatic shutdown
    
    // When the client disconnects
    ws.on('close', function() {
      console.log('Client disconnected');
      return process.exit(0);
    });
    // When server receives a command from client
    return ws.on('message', function(message) {
      var command, result;
      command = JSON.parse(message);
      //~ console.log 'Server received:', command.cmd
      switch (command.action) {
        case 'exec':
          // Execute native system command
          return exec(command.cmd, {
            timeout: command.timeout
          }, function(error, stdout, stderr) {
            var timeoutFlag;
            timeoutFlag = '';
            if (error && error.killed) {
              timeoutFlag = '#TIMEOUT';
            }
            return ws.send(`${stdout} ~~~ ${stderr} ~~~ ${error} ~~~ ${timeoutFlag}`);
          });
        case 'send':
          return data = command.cmd;
        case 'script':
          // Execute JavaScript code under Node.js
          console.log(command.cmd);
          try {
            result = eval(command.cmd);
          } catch (error1) {
            result = '#ERROR';
          }
          return ws.send(result);
      }
    });
  });

  
  // ---------------------------------------------------------------------
  openBrowser = function(url) {
    switch (process.platform) {
      case 'win32':
        return exec(`start ${url}`);
      case 'linux':
        return exec(`xdg-open '${url}'`);
      case 'darwin':
        return exec(`open '${url}'`);
      default:
        console.error('Unsupported operating system');
        return process.exit(1);
    }
  };

  // --------------------------------------
  launchBrowser = function(webpage, fragment) {
    console.log('Launching default browser at', webpage);
    return openBrowser(webpage + fragment);
  };

  // --------------------------------------
  shutdown = function() {
    if (timeout) {
      console.log('Client did not respond in time. Server closed.');
      return process.exit(1);
    }
  };

}).call(this);
